### ISSUE TITLE
Provide default values for BIG-IQ Application Tier fields, and close Application Tier twisty 

### ISSUE THREAD

**Issue by pdp2shirts** [0xHiteshPatel/appsvcs_integration_iapp#1]
On BIG-IQ, create a catalog item from the f5.http iApp notice that the "Application Tiers" fields all have default values and the twisty is closed. Can you do the same here with the appsvcs iApp?

![image](https://cloud.githubusercontent.com/assets/5025809/8388536/3209027a-1c18-11e5-83bd-799d64a4745a.png)

I had to open the twisty to see these fields. Doing this would greatly simplify the user experience.

**Comment by 0xHiteshPatel** [comment]
There are currently some static mappings in BIG-IQ to provide this functionality.  Already working on figuring out how we can make this better, however, it's low priority right now since selecting the proper values does work.  

Part of the real problem here is that there are some dependencies in BIG-IQ for the Virtual Server Address, Virtual Server Port and Pool mappings.  These require the use of the var name pool__addr and pool__port which is really confusing. I've created issue #6 to track this.

I've marked this as an enhancement since it should work properly at some point.  Right now we have to wait for BIG-IQ to expose a proper way to auto-populate the app tiers (or add a static mapping for us)

**Comment by 0xHiteshPatel** [comment]
This is being address in iWf 2.1 release two ways:
 1) Now that template is officially supported, iWf will ship with a default provider template
 2) iWf 2.1 add the ability to create provider templates via the API

These improvements should fully address this issue.
