### ISSUE TITLE
Support for Local Traffic Policies

### ISSUE THREAD

**Issue by vsnine** [0xHiteshPatel/appsvcs_integration_iapp#13]
Hello,

It would be nice if the iApp could be extended to support Local Traffic Policies. At a basic level it would allow for the entry of a policy name during execution, similarly to how iRules are assigned.

Thanks.

**Comment by 0xHiteshPatel** [comment]
You can already link in an existing Local Traffic Policy by using the 'Virtual Server: Advanced Profiles' ($vs__AdvProfiles) field.  The field supports a comma seperated list of policies to attach to the Virtual Server... any type of policy should work.

Creation of a policy is far more complicated and would require quite a bit more work.  It's definately something we would like to support, however, it's going to require quite a bit of work due to the data model we would have to expose.

**Comment by vsnine** [comment]
Agreed, I don't think building the Local Traffic Policy in this iApp is appropriate.

Attempting to specify a Local Traffic Policy (/Common/testlocaltrafficpolicy) in the Advanced Profiles field using the v1.1dev(003)_001 of the iApp results in the following error:
01020036:3: The requested profile (/Common/testlocaltrafficpolicy) was not found.

My guess is that this is because in the virtual server configuration, the LTP is under the policies {} directive.

I added this to the implementation section of the iApp in my lab, just before the virtual creation, and it gets deployed in the virtual service configuration.

append cmd "policies add \{/Common/testlocaltrafficpolicy \}"

**Comment by 0xHiteshPatel** [comment]
Looks like this is an feature we need to add.  Shouldn't take too much work... we have some preso layer cleanup that needs to happen so i'll lump everything together so thing's only have to change once.

**Comment by 0xHiteshPatel** [comment]
This was committed in d28b4ca

Please re-open this issue if there are any problems.
