### ISSUE TITLE
Support to specify or disable "Server Agent Name" in HTTP profile

### ISSUE THREAD

**Issue by vsnine** [0xHiteshPatel/appsvcs_integration_iapp#15]
It would be useful for the iApp to support a few modes for the Server Agent Name in the HTTP profile.

auto - leave at default/inherit
disabled - set field to "none"
user-specified - permit user to specify the value

An alternative is to just specify it using the create: syntax, as: create:server-agent-name=none

**Comment by 0xHiteshPatel** [comment]
I'm hesitant to add additional fields to the presentation layer because then where do we stop.  The create syntax was designed to address all these scenarios while keeping the preso layer as simple as possible (which then leads to a cleaner API interface).

That being said I will research internally how prevalent the use of the server-agent-name field is.  My guess is that few customers use this option, however, I may be wrong.

**Comment by vsnine** [comment]
I agree with the sentiment that this isn't important enough to warrant a presentation layer item. I have seen in a few best practices guides that changing or deleting the Server Name is recommended.
