### ISSUE TITLE
load_crypto_object loads certs/keys into /Common instead of partition

### ISSUE THREAD

**Issue by phenetrik** [0xHiteshPatel/appsvcs_integration_iapp#33]
When deploying the iApp into a partition and referencing a URL in the SSL certificate & key section, the iApp fails with error "010716c8:3: Application service <name> cannot own Certificate File <cert> in a different partition."

I see the following output in /var/tmp/scriptd.out which implies the certificate is loaded into /Common, instead of the correct partition.

e.g.
[01/31/17 13:56:48][<appname>][load_crypto_object] obj_name=/Common/<name>.key file_name=/var/tmp/<name>.key

**Comment by 0xHiteshPatel** [comment]
Could you set the Log Level to 10 as described here:

http://appsvcs-integration-iapp.readthedocs.io/en/v2.0_001/logdebug.html

as send the full output of /var/tmp/scriptd.out?

Please be sure to strip any private information.  You can send via email to h.patel at f5.com also.

**Comment by 0xHiteshPatel** [comment]
*Please not the repo/branch this issue was opened against is deprecated*

This issue has been fixed in my develop branch here:

https://github.com/0xHiteshPatel/f5-application-services-integration-iApp/commit/d531a525d3f213167d5facaf64b5b96063f47f05

I've submitted a pull request to include in the official version.
