### ISSUE TITLE
FYI: Here are the Keys that are populated to NSX manager when "Tenant Editable" is checked

### ISSUE THREAD

**Issue by pdp2shirts** [0xHiteshPatel/appsvcs_integration_iapp#5]
![image](https://cloud.githubusercontent.com/assets/5025809/8389303/155e0d04-1c23-11e5-883d-46f9eca12c59.png)

The Key name that is used by NSX seems to be different than the Key name presented to BIG-IQ GUI, NSX seems to be using the Variable names, so they need to be as descriptive as possible in say 50 characters or less.

**Comment by 0xHiteshPatel** [comment]
v0.3_003 of the presentation layer will improve this.  The pool__addr and pool__port variables have to stay that way for now because of statically created mappings in BIG-IQ that require those names.  Already working on getting that issue fixed so we can rename the var to a more descriptive (and correct) name.  See additional notes in issue #1 

Closing this issue since the root issue is the same as issue #1 .  Will keep that issue open until we have full resolution.
